### ISSUE TITLE
starts up but dosnt stay running

### ISSUE THREAD

**Issue by Xdoses** [moxaj/archbroski#1]
Having an issue. will start up and "run" but after a sec or two disapears from bottem right and dosnt show up i tsk man

**Comment by moxaj** [comment]
Hm, do you mean that the system tray icon disappears? Can you see the process in task manager? In any case, there should be a log directory next to the executable, and an `stdout.log` file inside, can you share it?

**Comment by Xdoses** [comment]
Yes The icon disappears from the system try. It is not in Task manager at all.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by moxaj** [comment]
Please post your logfile and I'll have a look at it! Without it, I can only speculate.

**Comment by Xdoses** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by moxaj** [comment]
I'm not sure how you are posting these messages, but I still can't see the logfile :(

**Comment by Xdoses** [comment]
[stdout.log](https://github.com/moxaj/archbroski/files/8207940/stdout.log)

**Comment by moxaj** [comment]
Ok, the app successfully starts up according to the logs. Are you sure the process is killed? Can you check in resource monitor?

![image](https://user-images.githubusercontent.com/7839686/157283964-7d01d30a-f55a-490a-bb60-010553cf47be.png)
^ here's how it looks for me.

If you can't find it there, do you perhaps have a virus scanner running? If so, can you check its logs?

**Comment by Xdoses** [comment]
Checked moniter, shows up at the bottem of the list as terminated, after so i disabled anti virus, Same deal no change. if you really want to look into it im more then welcome to help and allow you to remote in

**Comment by moxaj** [comment]
I have published a new release (v0.1.3) which adds additional logging. Simply replace your existing .exe, and run the new one. It's still going to crash, but hopefully the logs will say why.

**Comment by MarcBoud** [comment]
Hi, tried launching it multiple times, no success, here is the log:

2022-03-08T19:27:35.152088100+01:00 INFO app - log4rs up and running
2022-03-08T19:27:35.154359600+01:00 INFO app - archbroski up and running
2022-03-08T19:27:35.186311900+01:00 ERROR panic - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': C:\Users\vikto\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.3.2\src\lib.rs:1548
2022-03-08T19:27:59.297238800+01:00 INFO app - log4rs up and running
2022-03-08T19:27:59.298472+01:00 INFO app - archbroski up and running
2022-03-08T19:27:59.321248700+01:00 ERROR panic - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': C:\Users\vikto\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.3.2\src\lib.rs:1548
2022-03-08T19:28:34.417012+01:00 INFO app - log4rs up and running
2022-03-08T19:28:34.417853300+01:00 INFO app - archbroski up and running
2022-03-08T19:28:34.437272100+01:00 ERROR panic - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': C:\Users\vikto\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.3.2\src\lib.rs:1548


I wonder why the directory is hardcoded in in the error, is it related?

**Comment by moxaj** [comment]
@MarcBoud hey there, published a [new release](https://github.com/moxaj/archbroski/releases/tag/v0.1.4). No guarantees that it fixes it since I cannot reproduce this error on my system, but let's hope for the best. Also, the directory being hardcoded is not an issue, it's simply some additional information for me.

@Xdoses can you verify that you see the same error message in your log file?

**Comment by Xdoses** [comment]
Seems to be running now. i have no issues with it.

**Comment by Xdoses** [comment]
Though i am not able to open up the settings, what would be the defualt key?

**Comment by moxaj** [comment]
The settings can only be opened from the system tray - right click -> `Settings`.

**Comment by Xdoses** [comment]
Yes i understand that. when i hit setting  nothing pops up to change or anything

**Comment by Xdoses** [comment]
[stdout.log](https://github.com/moxaj/archbroski/files/8209274/stdout.log)

**Comment by moxaj** [comment]
Sigh, sorry, I think i'm working around the bugs of a dependency of mine. I'll see what I can do about the latest error.

**Comment by Xdoses** [comment]
All good, im here to help.

**Comment by moxaj** [comment]
@Xdoses Published a new release [here](https://github.com/moxaj/archbroski/releases/tag/v0.2.0). The issue might have been that you don't have a webview installed (which I think comes by default with new windows releases), so this time I have a windows installer which should take care of that. You can safely delete the existing executables and just use the installer / uninstaller.

**Comment by Xdoses** [comment]
alright I'll try it when I get home. I'll let you know how that goes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
